### ISSUE TITLE
Getting error during setup.

### ISSUE THREAD

**Issue by Maki9009** [JD-2006/Wav2Lip-CodeFormer-Local#1]
im getting this error, 

save me pls, 

Do you want to use a pre-existing conda environment? (yes/no): no
Directory 'CodeFormer' does not exist.
Traceback (most recent call last):
  File "E:\Wav2Lip-CodeFormer-Local\1-Setup.py", line 21, in <module>
    shutil.rmtree(directory)
  File "C:\Users\mahmo\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\mahmo\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\mahmo\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\mahmo\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\mahmo\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\mahmo\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 617, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'Wav2Lip\\.git\\objects\\pack\\pack-f3ee2480536ecb16911e6c58e1d3be37e53d1b28.idx'

I have an upcoming project..pls save me sir

**Comment by JD-2006** [comment]
Sorry for late reply. If you have not solved it through google searches, I have updated the setup script.

Also check:

1.    Run as Administrator: Try running the script as an administrator. Right-click on the script or the command prompt/terminal and choose "Run as Administrator."

2.    Close Processes: Make sure no other processes are using the 'Wav2Lip' and 'CodeFormer' directories or their contents. Close any open files or programs that might be using them.

3. Anti-virus or Anti-malware Software: Some anti-virus or anti-malware software may lock files and prevent them from being deleted. Temporarily disable such software and see if the issue persists.

4.   Check Permissions: Ensure that the user running the script has the necessary permissions to delete files and directories in the specified locations.
